### ISSUE TITLE
Possible to get Webpacked `level` to store data as plain old Strings or JSON objects?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/webpack-starter#7]
When running this project, `level` seems to store text ('beep' and 'boop') as some kind of buffer. Is it possible to get Webpacked `level` to store data as plain old Strings or JSON objects? (I have experienced this behavior in other projects as well)

<img width="814" alt="Screenshot 2020-11-13 at 19 33 52" src="https://user-images.githubusercontent.com/1122333/99108517-c227e680-25e7-11eb-952e-4bb05937416f.png">

**Comment by vweevers** [comment]
Storing data as binary was a conscious decision in order to solve various issues: https://github.com/Level/memdown/issues/186.

**Comment by fergiemcdowall** [comment]
Fair enough- I can see that that makes sorting better for dbs with dynamically typed keys.

If a webpacked `level` db uses `String` keys and `Object` values, what is the best way to examine the contents of that db in a web browser? Is it possible to do so?

**Comment by vweevers** [comment]
Inspecting it with javascript is the only way, because the browser doesn't know what the binary data represents, same as with leveldb in node. I suppose you could write a devtools extension 🙃

**Comment by fergiemcdowall** [comment]
> I suppose you could write a devtools extension

I'm almost, _almost_ tempted to do so 😉
